"""extend password hash

Revision ID: 61debc41aaeb
Revises: a74199f7d313
Create Date: 2026-01-05 17:55:26.272475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61debc41aaeb'
down_revision = 'a74199f7d313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
